import json
import os
from pathlib import Path

import dacite
import numpy as np
import pandas as pd
from dacite import from_dict
from omegaconf import OmegaConf
from snakemake.utils import Paramspace, validate

import mussel.cli.annotate
import mussel.cli.cache_tiles
import mussel.cli.create_class_embeddings
import mussel.cli.extract_features
import mussel.cli.tessellate
from mussel.cli.annotate import AnnotateConfig
from mussel.cli.cache_tiles import CacheTilesConfig
from mussel.cli.create_class_embeddings import ClassEmbeddingConfig
from mussel.cli.extract_features import ExtractFeaturesConfig, Model
from mussel.cli.tessellate import (FilterConfig, PatchConfig, SegConfig,
                                   TessellateConfig, VisConfig)

os.umask(0o000)

configfile: "config/config.yaml"
validate(config, "../config/config.schema.yaml")

slide_df = pd.read_csv("slide_manifest.csv", dtype='string')
validate(slide_df, "../config/slides.schema.yaml")
slide_df.set_index("image_id", inplace=True, drop=False)

if config.get("annotation_class_csv"):
  annotation_df = pd.read_csv(config['annotation_class_csv'])
  validate(annotation_df, "../config/annotation.schema.yaml")
  slide_df = slide_df.merge(annotation_df, on='oncotree_code', how='left')

if not config['all_slides']:
  slides = [line.strip() for line in open(config['slide_list_path'], 'r')]
else:
  slides = slide_df.image_id

if config['test']:
  slides = slides[0:2]
slide_df = slide_df.loc[slides, :]

parameters = dict()
if config.get('parameters_csv_path'):
  parameters = pd.read_csv(config['parameters_csv_path'])
validate(parameters, "../config/params.schema.yaml")

 # sort the parameters for consistent paramspace patterns
if type(parameters) == dict:
  df = pd.DataFrame([parameters])
  df = df.reindex(sorted(df.columns), axis=1)
  paramspace = Paramspace(df, param_sep='--')
else:
  parameters = parameters.reindex(sorted(parameters.columns), axis=1)
  paramspace = Paramspace(parameters, param_sep='--')


def create_config(config_class, wildcards, **kwargs):
  # convert np types to native python types
  instance = { k:val.item() if type(val).__module__ == np.__name__ else val for k, val in paramspace.instance(wildcards).items() }
  instance.update(**kwargs)
  return from_dict(data_class=config_class, data=instance, config=dacite.Config(cast=[Model]))


def get_slide(wildcards):
  return slide_df.loc[wildcards.slide_id, "url"]

def get_slide_oncotree(wildcards):
  return slide_df.loc[wildcards.slide_id, ["url", "oncotree_code"]]

def get_annotation_classes(wildcards):
  if 'annotation_class_json' in slide_df.columns:
    annotation_class_json = slide_df.loc[wildcards.slide_id, 'annotation_class_json']
    if annotation_class_json:
      return json.load(annotation_class_json)
  return config["default_annotation_classes"]

def get_annotation_classes_to_cache(wildcards):
  if 'annotation_class_to_cache_json' in slide_df.columns:
    annotation_class_to_cache_json = slide_df.loc[wildcards.slide_id, 'annotation_class_to_cache_json']
    if annotation_class_to_cache_json:
      return json.load(annotation_class_to_cache_json)
  return config["default_annotation_classes_to_cache"]


rule all:
  input:
    expand(f"{config['reef_dir']}/{{params}}/features/pt/{{slide_id}}.pt", params=paramspace.instance_patterns, slide_id=slides)

rule tiles:
  input:
    expand(f"{config['reef_dir']}/{{params}}/tessellate/h5/{{slide_id}}.h5", params=paramspace.instance_patterns, slide_id=slides)

rule tessellate:
  output:
    patch_h5_path=protected(f"{config['reef_dir']}/{paramspace.wildcard_pattern}/tessellate/h5/{{slide_id}}.h5"),
    stitch_path=protected(f"{config['reef_dir']}/{paramspace.wildcard_pattern}/tessellate/stitches/{{slide_id}}.jpg"),
  log: f"logs/{paramspace.wildcard_pattern}/tessellate/{{slide_id}}.log"
  resources:
    request_memory="30GB"
  run:
    slide_path = get_slide(wildcards)
    cfg = create_config(TessellateConfig,
                        wildcards,
                        slide_path=slide_path,
                        output_h5_path=output.patch_h5_path,
                        stitch_jpeg_path=output.stitch_path,
                        seg_config=create_config(SegConfig, wildcards),
                        patch_config=create_config(PatchConfig, wildcards),
                        filter_config=create_config(FilterConfig, wildcards),
                        vis_config=create_config(VisConfig, wildcards),
                        )
    mussel.cli.tessellate.main(OmegaConf.create(cfg))


rule featurize:
  input:
    patch_h5_path=f"{config['reef_dir']}/{paramspace.wildcard_pattern}/tessellate/h5/{{slide_id}}.h5",
  output:
    pt=protected(f"{config['reef_dir']}/{paramspace.wildcard_pattern}/features/pt/{{slide_id}}.pt"),
    h5=protected(f"{config['reef_dir']}/{paramspace.wildcard_pattern}/features/h5/{{slide_id}}.h5"),
  log: f"logs/{paramspace.wildcard_pattern}/featurize/{{slide_id}}.log"
  threads: 32
  resources:
    request_memory="30GB",
    request_gpus=1
  run:
    slide_path = get_slide(wildcards)
    cfg = create_config(ExtractFeaturesConfig,
                        wildcards,
                        patch_h5_path=input.patch_h5_path,
                        output_h5_path=output.h5,
                        output_pt_path=output.pt,
                        slide_path=slide_path,
                        num_workers=threads,
                        transpath_dir=config.get('transpath_dir'),
                        transpath_model_path=config.get('transpath_model_path'),
                        quiltnet_model_path=config.get('quiltnet_model_path'),
                        batch_size=config['batch_size'],
                        use_gpu=config['use_gpu'],
                        gpu_device_ids=config.get('gpu_device_ids'),
                        )
    mussel.cli.extract_features.main(OmegaConf.create(cfg))


rule class_embedding:
  output:
    f"{config['reef_dir']}/class_embeddings/{{oncotree_code}}.pt"
  run:
    classes = get_annotation_classes(wildcards)
    cfg = OmegaConf.create(ClassEmbeddingConfig(classes=classes,
                                                quiltnet_model_path=config['quiltnet_model_path'],
                                                output_pt_path=output[0]))
    mussel.cli.create_class_embeddings.main(cfg)

quiltnet_mask = paramspace['model'] == "quiltnet"
if sum(quiltnet_mask) > 0:
  quiltnet_paramspace = Paramspace(paramspace[quiltnet_mask], param_sep='--')

  rule annotations:
    input:
      expand(f"{config['reef_dir']}/{{params}}/annotations/{{s.oncotree_code}}/{{s.image_id}}.csv", params=quiltnet_paramspace.instance_patterns, s=list(slide_df.itertuples()))

  rule stacked_annotations:
    input:
      expand(f"{config['reef_dir']}/{{params}}/stacked_annotations/{{oncotree_code}}.csv",
             params=quiltnet_paramspace.instance_patterns,
             oncotree_code=slide_df['oncotree_code'].unique())

  rule stack_oncotree_code_annotations:
    input:
      expand(f"{config['reef_dir']}/{quiltnet_paramspace.wildcard_pattern}/annotations/{{oncotree_code}}/{{sample.image_id}}.csv",
             sample=lookup(query="oncotree_code == '{oncotree_code}'", within=slide_df), allow_missing=True)
    output:
      f"{config['output_dir']}/{quiltnet_paramspace.wildcard_pattern}/stacked_annotations/{{oncotree_code}}.csv"
    run:
      li = []
      for filename in input:
        slide_id = Path(filename).stem
        df = pd.read_csv(filename, index_col=None, header=0)
        df.insert(loc=0, column='slide_id', value=slide_id)
        li.append(df)

      frame = pd.concat(li, axis=0, ignore_index=True)
      frame.to_csv(output[0], index=False)

  rule cached_tiles:
    input:
      expand(f"{config['reef_dir']}/{{params}}/cache_tiles/{{s.oncotree_code}}/pt/{{s.image_id}}.pt", params=quiltnet_paramspace.instance_patterns, s=list(slide_df.itertuples()))

  rule annotate:
    input:
      features=f"{config['reef_dir']}/{quiltnet_paramspace.wildcard_pattern}/features/pt/{{slide_id}}.pt",
      class_embedding=f"{config['reef_dir']}/class_embeddings/{{oncotree_code}}.pt",
    output:
      f"{config['reef_dir']}/{quiltnet_paramspace.wildcard_pattern}/annotations/{{oncotree_code}}/{{slide_id}}.csv"
    log: f"logs/{quiltnet_paramspace.wildcard_pattern}/annotate/{{oncotree_code}}/{{slide_id}}.log"
    resources:
      request_memory="12GB"
    run:
      classes = get_annotation_classes(wildcards)
      cfg = create_config(
          AnnotateConfig,
          wildcards,
          features_pt_path=input.features,
          classes=classes,
          class_embedding_pt_path=input.class_embedding,
          output_csv_path=output[0],
          )
      mussel.cli.annotate.main(OmegaConf.create(cfg))

  rule cache_tiles:
    input:
      patch_h5=f"{config['reef_dir']}/{quiltnet_paramspace.wildcard_pattern}/tessellate/h5/{{slide_id}}.h5",
      annotation_csv=f"{config['reef_dir']}/{quiltnet_paramspace.wildcard_pattern}/annotations/{{oncotree_code}}/{{slide_id}}.csv",
    output:
      pt=f"{config['reef_dir']}/{quiltnet_paramspace.wildcard_pattern}/cache_tiles/{{oncotree_code}}/pt/{{slide_id}}.pt",
      indices=f"{config['reef_dir']}/{quiltnet_paramspace.wildcard_pattern}/cache_tiles/{{oncotree_code}}/indices/{{slide_id}}.json",
    log: f"logs/{quiltnet_paramspace.wildcard_pattern}/cache_tiles/{{oncotree_code}}/{{slide_id}}.log"
    resources:
      request_memory="24GB"
    run:
      slide_path = get_slide(wildcards)
      limit_to_class = get_annotation_classes_to_cache(wildcards)
      cfg = create_config(
          CacheTilesConfig,
          wildcards,
          patch_h5_path=input.patch_h5,
          slide_path=slide_path,
          num_workers=threads,
          annotation_csv_path=input.annotation_csv,
          limit_to_class=limit_to_class,
          output_indices_json_path=output.indices,
          output_pt_path=output.pt,
          )
      mussel.cli.cache_tiles.main(OmegaConf.create(cfg))


  if 'annotation_class_json_path' in config:
    rule custom_annotations:
      input:
        expand(f"{config['output_dir']}/{{params}}/annotations/{{slide_id}}.csv", params=quiltnet_paramspace.instance_patterns, slide_id=slides)

    rule custom_cached_tiles:
      input:
        expand(f"{config['output_dir']}/{{params}}/cache_tiles/pt/{{slide_id}}.pt", params=quiltnet_paramspace.instance_patterns, slide_id=slides)


    rule custom_class_embedding:
      input:
        config['annotation_class_json_path']
      output:
        f"{config['output_dir']}/class_embedding.pt"
      run:
        os.umask(0o022)
        with open(input[0]) as f:
          classes = json.load(f)
        cfg = OmegaConf.create(ClassEmbeddingConfig(classes=classes,
                                                    quiltnet_model_path=config['quiltnet_model_path'],
                                                    output_pt_path=output[0]))
        mussel.cli.create_class_embeddings.main(cfg)

    rule custom_stacked_annotations:
      input:
        expand(f"{config['output_dir']}/{{params}}/stacked_annotations.csv",
              params=quiltnet_paramspace.instance_patterns)

    rule custom_stack_oncotree_code_annotations:
      input:
        expand(f"{config['output_dir']}/{{params}}/annotations/{{slide_id}}.csv", params=quiltnet_paramspace.instance_patterns, slide_id=slides)
      output:
        f"{config['output_dir']}/{quiltnet_paramspace.wildcard_pattern}/stacked_annotations.csv"
      run:
        li = []
        for filename in input:
          slide_id = Path(filename).stem
          df = pd.read_csv(filename, index_col=None, header=0)
          df.insert(loc=0, column='slide_id', value=slide_id)
          li.append(df)

        frame = pd.concat(li, axis=0, ignore_index=True)
        frame.to_csv(output[0], index=False)


    rule custom_annotate:
      input:
        features=f"{config['reef_dir']}/{quiltnet_paramspace.wildcard_pattern}/features/pt/{{slide_id}}.pt",
        class_embedding=f"{config['output_dir']}/class_embedding.pt",
        class_json=config['annotation_class_json_path']
      output:
        f"{config['output_dir']}/{quiltnet_paramspace.wildcard_pattern}/annotations/{{slide_id}}.csv"
      log: f"logs/{quiltnet_paramspace.wildcard_pattern}/annotate/{{slide_id}}.log"
      resources:
        request_memory="12GB"
      run:
        os.umask(0o022)
        with open(input.class_json) as f:
          classes = json.load(f)
        cfg = create_config(
            AnnotateConfig,
            wildcards,
            features_pt_path=input.features,
            classes=classes,
            class_embedding_pt_path=input.class_embedding,
            output_csv_path=output[0],
            )
        mussel.cli.annotate.main(OmegaConf.create(cfg))

    rule custom_cache_tiles:
      input:
        patch_h5=f"{config['reef_dir']}/{quiltnet_paramspace.wildcard_pattern}/tessellate/h5/{{slide_id}}.h5",
        annotation_csv=f"{config['output_dir']}/{quiltnet_paramspace.wildcard_pattern}/annotations/{{slide_id}}.csv",
      output:
        pt=f"{config['output_dir']}/{quiltnet_paramspace.wildcard_pattern}/cache_tiles/pt/{{slide_id}}.pt",
        indices=f"{config['output_dir']}/{quiltnet_paramspace.wildcard_pattern}/cache_tiles/indices/{{slide_id}}.json",
      log: f"logs/{quiltnet_paramspace.wildcard_pattern}/cache_tiles/{{slide_id}}.log"
      resources:
        request_memory="24GB"
      run:
        os.umask(0o022)
        classes = None
        if 'annotation_class_to_cache_json' in config:
          with open(config['annotation_class_to_cache_json_path']) as f:
            classes = json.load(f)
        slide_path = get_slide(wildcards)
        cfg = create_config(
            CacheTilesConfig,
            wildcards,
            patch_h5_path=input.patch_h5,
            slide_path=slide_path,
            num_workers=threads,
            annotation_csv_path=input.annotation_csv,
            limit_to_class=classes,
            output_indices_json_path=output.indices,
            output_pt_path=output.pt,
            )
        mussel.cli.cache_tiles.main(OmegaConf.create(cfg))

