$schema: "https://json-schema.org/draft-06/schema#"
description: snakemake configuration
properties:
  parameters:
    $ref: "file://params.schema.yaml#/properties"
  slide_directory_file:
    type: string
    default: slide_directory.csv
    description: slide directory csv
  parameters_file:
    type: string
    description: parameter space csv
  batch_size:
    type: integer
    default: 8
    description: batch size 
  transpath_dir:
    type: string
    description: CTransPath dir
  use_gpu:
    type: boolean
    default: true
    description: Use GPU





