$schema: "https://json-schema.org/draft/2020-12/schema"
description: snakemake configuration
properties:
  slide_directory_file:
    type: string
    default: slide_directory.csv
    description: slide directory csv
  parameters_file:
    type: string
    description: parameter space csv
  batch_size:
    type: integer
    default: 8
    description: batch size
  transpath_dir:
    type: string
    description: CTransPath dir
  use_gpu:
    type: boolean
    default: true
    description: Use GPU
  test:
    type: boolean
    default: false
    description: test mode
  quiltnet_model_path:
    type: string
    description: Path to quiltnet model
    default: "hf-hub:wisdomik/QuiltNet-B-16-PMB"
  transpath_model_path:
    type: string
    description: Path to CTransPath model
