name: mussel
channels:
  - conda-forge
  - pytorch
  - nodefaults
dependencies:
  - python
  - pandas
  - numpy
  - opencv
  - h5py
  - matplotlib
  - tiffslide
  - pytorch
  - torchvision
  - hydra-core
  - dacite
  - open-clip-torch
  - transformers
  - sentencepiece
  - loguru
  - pyarrow
  - pip
platforms:
  - linux-64
  - osx-64
  - osx-arm64
