name: mussel
dependencies:
  - python==3.12.0
  - pip
  - pip:
    - pandas
    - numpy
    - opencv-python
    - h5py
    - matplotlib
    - tiffslide
    - torch
    - torchvision
    - hydra-core
    - dacite
    - open-clip-torch
    - transformers
    - sentencepiece
    - loguru 
    - pyarrow