name: mussel
dependencies:
  - python==3.12.0
  - conda-forge::openslide
  - conda-forge::openslide-python
  - pip
  - pip:
    - pandas
    - numpy
    - opencv-python
    - h5py
    - matplotlib
    - torch
    - torchvision
    - hydra-core
    - dacite
    - open-clip-torch
    - transformers
    - sentencepiece
    - loguru 
    - pyarrow