[project]
name = "mussel"
version = "0.1.0"
description = "weakly supervised computational pathology on whole slide images"
license = {text = "GPL-3.0 license"}
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["dependencies", "optional-dependencies"]

[tool.unidep]
channels = ["conda-forge", "pytorch", "nodefaults"]
dependencies = [
  { conda = "python>=3.12" },
  "pandas",
  "numpy",
  "h5py",
  "matplotlib",
  "tiffslide",
  { conda = "opencv", pip = "opencv-python-headless" },
  { conda = "pytorch", pip = "torch" },
  "torchvision",
  "hydra-core",
  "dacite",
  "open-clip-torch",
  "transformers",
  "sentencepiece",
  "loguru",
  "pyarrow",
  { conda = "pip" }
]
platforms = [
  "linux-64",
  "osx-64",
  "osx-arm64"
]

[tool.unidep.optional_dependencies]
dev = ["mypy", "unidep"]
test = ["pytest"]

[tool.setuptools]
packages = ["mussel", "mussel.cli"]

[build-system]
requires = ["setuptools", "unidep[toml]"]
build-backend = "setuptools.build_meta"

[project.scripts]
annotate = 'mussel.cli.annotate:main'
cache_tiles = 'mussel.cli.cache_tiles:main'
extract_features = 'mussel.cli.extract_features:main'
tessellate = 'mussel.cli.tessellate:main'
create_class_embeddings = 'mussel.cli.create_class_embeddings:main'
