[project]
name = "mussel"
version = "0.9.0"
description = "weakly supervised computational pathology on whole slide images"
license = {text = "GPL-3.0 license"}
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
  "pandas",
  "numpy",
  "h5py",
  "matplotlib",
  "tiffslide",
  "opencv-python-headless",
  "hydra-core",
  "dacite",
  "transformers",
  "sentencepiece",
  "loguru",
  "pyarrow",
  "geopandas",
  "scikit-learn",
  "pydantic",
  "transpath@git+https://github.com/msk-mind/TransPath/",
  "timm_ctranspath@git+https://github.com/msk-mind/timm-ctranspath",
  "mdutils>=1.6.0",
  "shapely>=2.0.7",
]

[dependency-groups]
dev = [
    "mypy",
    "isort",
    "black",
    "pytest",
    "ipython>=9.1.0",
    "jupyter>=1.1.1",
]

[project.optional-dependencies]
"tensorflow-gpu" = [
  "tensorflow[and-cuda]",
  "keras",
  "tf-keras",
  "torch < 2.6",
  "torchvision",
  "open-clip-torch",
]
"tensorflow-cpu" = [
  "tensorflow",
  "keras",
  "tf-keras",
  "torch < 2.6",
  "torchvision",
  "open-clip-torch",
]
"torch-cpu" = [
  "torch < 2.6",
  "torchvision",
  "open-clip-torch",
]
"torch-gpu" = [
  "torch < 2.6",
  "torchvision",
  "open-clip-torch",
]

[tool.uv]
conflicts = [
    [
      { extra = "tensorflow-gpu" },
      { extra = "tensorflow-cpu" },
      { extra = "torch-cpu" },
      { extra = "torch-gpu" },
    ],
]

[tool.uv.sources]
torch = [
  { index = "torch-cpu", extra = "tensorflow-gpu" },
  { index = "torch-cpu", extra = "tensorflow-cpu" },
  { index = "torch-cpu", extra = "torch-cpu" },
  { index = "torch-gpu", extra = "torch-gpu" },
]
torchvision = [
  { index = "torch-cpu", extra = "tensorflow-gpu" },
  { index = "torch-cpu", extra = "tensorflow-cpu" },
  { index = "torch-cpu", extra = "torch-cpu" },
  { index = "torch-gpu", extra = "torch-gpu" },
]

[[tool.uv.index]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "torch-gpu"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.setuptools.packages.find]
include = ["mussel*"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
annotate = 'mussel.cli.annotate:main'
cache_tiles = 'mussel.cli.cache_tiles:main'
extract_features = 'mussel.cli.extract_features:main'
filter_features = 'mussel.cli.filter_features:main'
tessellate = 'mussel.cli.tessellate:main'
create_class_embeddings = 'mussel.cli.create_class_embeddings:main'
stitch_tiles = 'mussel.cli.stitch_tiles:main'
merge_annotation_features = 'mussel.cli.merge_annotation_features:main'
linear_probe_benchmark = 'mussel.cli.linear_probe_benchmark:main'
