from snakemake.utils import validate

configfile: "config/dremio_config.yaml"
validate(config, "../config/dremio_config.schema.yaml")

envvars:
  "DREMIO_USERNAME",
  "DREMIO_PASSWORD"

rule slide_manifest:
  log: "logs/slide_directory.log"
  output:
    "slide_manifest.csv"
  params:
    username=os.environ["DREMIO_USERNAME"],
    password=os.environ["DREMIO_PASSWORD"],
  script: "scripts/get_slide_directory.py"
