from .model_factory import (
    ModelFactory,
    ModelType,
    get_model_factory,
    validate_slide_encoder_compatibility,
    get_required_patch_encoder,
    get_default_patch_size,
    SLIDE_ENCODER_COMPATIBILITY,
    MODEL_PATCH_SIZES,
)

# Import model modules to trigger @register_model self-registration
from . import (
    clip,
    chief,
    conch,
    conch_v1,
    feather,
    genbio,
    gigapath,
    googlepath,
    gpfm,
    hibou,
    kaiko,
    lunit,
    madeleine,
    midnight,
    openmidnight,
    optimus,
    phikon,
    prism,
    resnet,
    transpath,
    uni,
    virchow,
)
