$schema: "https://json-schema.org/draft/2020-12/schema"
description: annotation json for each oncotree code
properties:
  oncotree_code:
    type: string
    description: oncotree code
  annotation_class_json:
    type: string
    description: annotation class json
  annotation_class_to_cache_json:
    type: string
    description: annotation classes to cache json
required:
  - oncotree_code
  - annotation_class_json
