$schema: "https://json-schema.org/draft/2020-12/schema"
description: Mussel snakemake configuration
properties:
  scheme:
    type: string
    default: "grpc+tcp"
  hostname:
    type: string
  port:
    type: integer
    default: 32010
  space:
    type: string
    default: "pathology-data-mining.mussel"
  table:
    type: string
    default: "slide_manifest"
