$schema: "https://json-schema.org/draft/2020-12/schema"
description: an entry in the slide sheet
properties:
  image_id:
    type: string
    description: image ID
  url:
    type: string
    description: image file url
  oncotree_code:
    type: string
    description: oncotree code

required:
  - image_id
  - url
  - oncotree_code
