universe = vanilla
executable = train.sh 
arguments = config/$(config).yaml

# "short", "medium", "long" for jobs lasting
# ~12 hr, ~24 hr, ~7 days
+GPUJobLength = "short"

# machine requirements to match classad
# requirements = (Machine == "pllimskhpc2") && (TotalGpus > 0)

# resource
request_gpus = 1
request_memory = 100GB
request_cpus = 64
#request_disk = 10MB

output = condor_logs/$(config).out
log = condor_logs/$(config).log
error = condor_logs/$(config).err

queue config from (
Omar-Condor
)
